### PR TITLE
Refactor `Activity.kwargs` into `Activity.extras` to facilitate its usage

### PR DESCRIPTION
**Pull request by tboye**
`Activity` model had a field called `kwargs` that was intended to hold additional info about events. By the looks of the code and [data.gouv.fr](https://www.data.gouv.fr/api/1/activity?page=1&page_size=20), it hasn't been really used while it could be very helpful.

When trying to incorporate this field, it appeared that its name clashes with `**kwargs` argument used in dependent libraries. To avoid issues, this field was renamed into `extras` along with changing its type to `ExtrasField` to make it aligned with other models.

Migration shouldn't be a problem due to the fact this field is not in use.

@maudetes Please let me know if you agree with this change and I can add a migration script and adjust tests.

### CODE REVIEW

**Review by maudetes — COMMENTED** [review]
It sounds like a good idea! Thank you for this PR :pray:
Do you have an idea of the kind of extras you would add?

**Comment by tboye** [comment]
@maudetes A few things I currently have in mind:
- attaching a diff to dataset updated activities
- attaching a reason to dataset deletion activities

**Comment by maudetes** [comment]
Nice! I'll let you add the migration script and some tests and you can ask me again for review then :)

**Comment by tboye** [comment]
Ready for review @maudetes

**Review by maudetes — APPROVED** [review]
Thank you again for this PR! Looks good to me

**Pull request merged**
