### PR TITLE
Removed unused js files (fix #2229)

### LINKED ISSUE #2229: Dead code: Unused js files
```
WARNING in 
UnusedFilesWebpackPlugin found some unused files:
js/api.light.js
js/components/dataset/resource/card.vue
js/components/harvest/mappings-form.vue
js/components/harvest/source-form.vue
js/components/reuse/datasets-list.vue
js/index.md
js/locales/udata.ar.json
js/oembed.js
js/site.js
js/widgets.js
```

Except `oembed.js` and `widgets.js` that are standalones, other ones seem deletable.

### PR DESCRIPTION
**Pull request by noirbizarre**
This PR remove some unused JS files following #2229 report.

Kept files are:
- `js/locales/udata.ar.json`: https://crowdin.com/project/udata/ar
- `js/oembed.js`: [main oembed build entry point](https://github.com/opendatateam/udata/blob/master/webpack.config.oembed.js#L7)
- `js/widgets.js`: [main legacy widgets build entry point](https://github.com/opendatateam/udata/blob/master/webpack.config.widgets.js#L5)

### CODE REVIEW

**Comment by taniki** [comment]
Commence ça se fait que `udata.ar.json` apparaissent dans le reporting des fichiers pas utilisés alors que les autres langues non ?

**Comment by taniki** [comment]
Spotted. Il faut choisir entre rajouter 'ar' ici https://github.com/opendatateam/udata/blob/86a648fdf8388c2b27a38520e56b0629e1c003b7/webpack.config.js#L11 ou abandonner la traduction

**Comment by noirbizarre** [comment]
Yes, it's not activated because the translation is in progress. Dropping the file won't let them finish the translation as their work will be lost

**Comment by taniki** [comment]
Who are "they"? Are they still on it? (: At least open an issue about the unfinished business (: cc @bzg

**Comment by noirbizarre** [comment]
They == Data4Tunisia == @trojette

**Comment by taniki** [comment]
@sandcha do you have an update about this?

**Comment by bzg** [comment]
The translation effort is still going on, so `js/locales/udata.ar.json` should stay until `ar` can be added as a supported language in `udata/webpack.config.js`.

This is not a blocking issue, this PR can be merged.

**Pull request merged**
