### PR TITLE
Properly set a reference to a user in Discussion.closed_by when importing the fixtures

### PR DESCRIPTION
**Pull request by magopian**
When running `udata import-fixtures`, the fixtures were creating discussions which were closed with a `closed_by` filled with the dictionnary of the user closing the discussion, instead of a reference to the user, causing server errors when listing such discussions.

### CODE REVIEW

**Review by maudetes — APPROVED** [review]
Don't forget to add a changelog entry! Was this problem not occurring before the refacto?

**Comment by magopian** [comment]
I believe it was occuring before the refacto, but it wasn't easily spotted, as not many discussions were closed: I can see that 11 out of the nearly 150 discussions are closed in the [legacy fixtures](https://github.com/opendatateam/udata-fixtures/blob/v1.0.0/results.json) (search for `"closed_by": {`).

I'm adding the CHANGELOG and rebasing the branch on master, and then will merge it, thanks for the review 🙏

**Comment by magopian** [comment]
Oops, I see that I got lost in the refactoring to properly set users everywhere... and forgot to properly test (and set) the `closed_by` user... I rebased the PR, and added the test and code needed, would you mind reviewing it again @maudetes ? 😬

**Review by maudetes — APPROVED** [review]
I think we're clear? :D

**Pull request merged**
