### PR TITLE
Adds the dataset acronym to the indexed fields

### PR DESCRIPTION
**Pull request by abulte**
Replaces #2367, courtesy of @odtvince

### CODE REVIEW

**Comment by abulte** [comment]
This yields unconvincing results on next.data.gouv.fr : neither SIREN nor DVF queries yield more pertinent (first) result, in fact nothing seems to change but that was some quick testing.

**Comment by AntoineAugusti** [comment]
Curious if you investigated a bit about this. Was it indexed eventually? Did you troubleshoot?

**Comment by abulte** [comment]
Nothing more than last test above, this is very nebulous.

**Comment by ThibaudDauce** [comment]
I think we can close this :-) Feel free to open an issue if it's still a problem we want to fix :-)

**Pull request closed without merging**
