### PR TITLE
fix: fix reports/reasons endpoint output

### PR DESCRIPTION
**Pull request by bolinocroustibat**
Closes https://github.com/datagouv/data.gouv.fr/issues/1391

### CODE REVIEW

**Review by ThibaudDauce — APPROVED** [review]
Could you update this line of documentation?
```
    @ns.response(200, "dictionnary of available reasons associated with their labels", fields.Raw)
```

Otherwise, good for me!

**Review by nicolaskempf57 — APPROVED** [review]
Perfect for udata-front :)

**Comment by ThibaudDauce** [comment]
You can also add the link to this PR to the changelog line about reports backend :-)

**Comment by bolinocroustibat** [comment]
> Could you update this line of documentation?
> 
> ```
>     @ns.response(200, "dictionnary of available reasons associated with their labels", fields.Raw)
> ```
> 
> Otherwise, good for me!

Well spotted, done

**Comment by bolinocroustibat** [comment]
> Perfect for udata-front :)

Indeed, done

**Pull request merged**
