### PR TITLE
Conditional community resources anchor

### PR DESCRIPTION
**Pull request by abulte**
As suggested by @cquest.

It was also suggested to add the number of community resources in the anchor link, but I feel it would be too much information. Please advise.

### CODE REVIEW

**Comment by abulte** [comment]
@noirbizarre right, I did not think about the "you can add one yourself" argument. So now I'm not so sure... @taniki WDYT?

**Comment by abulte** [comment]
Since we don't explain how a community resource can be useful when there is none, I'd still lean toward hiding the link when there's none.

**Comment by taniki** [comment]
I would recommend to separate section header and the link. Also indicate that's an interactive element with some wording. The repetition of "resource" is not very aesthetic too.

Conditional is fine. A counter will be good too to add density but then I will be weird to show it only if there is community resources.

screenshot-2018-5-30 base sirene des entreprises et de leurs etablissements siren siret - data gouv fr

**Comment by abulte** [comment]
capture d ecran 2018-05-31 17 38 57

**Pull request merged**
