### PR TITLE
 Restore placeholders in search suggestions, fix #790

### LINKED ISSUE #790: Restore placeholders in search suggestions
capture d ecran 2017-02-20 a 22 31 53

### PR DESCRIPTION
**Pull request by davidbgk**
Note that it doesn't work for now. Some trickery is removing the image once displayed (after one thick?). Help @noirbizarre ?

### CODE REVIEW

**Comment by noirbizarre** [comment]
You need to expose `placeholders` into the component scope. The easiest would be to add it into `data()`

**Comment by noirbizarre** [comment]
(Add a changelog entry)

**Comment by davidbgk** [comment]
@noirbizarre thanks, it works well for territories where I have both existing logos and the placeholder fallback. **But** for datasets and organizations I still have the flashing image this time for the existing logo! I guess it's somehow a caching issue that doesn't happen with territories because that's the last item of the list?

**Comment by noirbizarre** [comment]
What do you mean by flashing issue ?

**Comment by noirbizarre** [comment]
Is it mergeable for 1.0.4 and then we find a solution for the flashing issue or do you prefer to wait for a solution ?

**Comment by davidbgk** [comment]
@noirbizarre I mean that it appears and disappears immediately after that, like if it was somehow overridden by another VueJS update?

**Comment by davidbgk** [comment]
> Is it mergeable for 1.0.4 and then we find a solution for the flashing issue or do you prefer to wait for a solution ?

It's better but far from ideal, I think it lacks a minor fix to make it works.

**Comment by noirbizarre** [comment]
Proposition: let's merge it and try to find a fix a soon as possible, agreed ?

**Comment by davidbgk** [comment]
Alright, let's do it.

**Pull request merged**
