### PR TITLE
Add some more integrity migrations fix

### PR DESCRIPTION
**Pull request by maudetes**
More iteration on https://github.com/etalab/data.gouv.fr/issues/460.

Some more integrity fixes after trying https://github.com/opendatateam/udata/pull/2644 on demo env.

Questions:
- Not sure what to do with actual HarvestJob items errors in migration.
- How to prevent HarvestJob items errors?
- Shouldn't `reverse_delete_rule=db.CASCADE` prevent `HarvestJob.source(HarvestSource)` errors already?

### CODE REVIEW

**Review by abulte — COMMENTED** [review]
We should add removing dataset from HarvestJob when purging it.

**Comment by abulte** [comment]
> Shouldn't reverse_delete_rule=db.CASCADE prevent HarvestJob.source(HarvestSource) errors already?

Yup. Maybe stuff from more than two years old?

https://github.com/opendatateam/udata/commit/9f1dac26a0c9960a0dec5d78a8b1af0c0a6cd53f

But the way, we have a job to truncate harvest job history, maybe it's not scheduled on demo.

**Comment by abulte** [comment]
`purge-harvest-jobs` is scheduled nowhere :-/ we should do that.

**Comment by abulte** [comment]
Just launched `purge-harvest-jobs` on demo.

**Comment by abulte** [comment]
```
➢ Running job purge-harvest-jobs
➢ ➢ Running job purge-harvest-jobs
➢ Purging HarvestJobs older than retention policy
➢ ➢ Purging HarvestJobs older than retention policy
➢ Job purge-harvest-jobs done
➢ ➢ Job purge-harvest-jobs done
```

**Comment by maudetes** [comment]
After purge-harvest-jobs, still many errors on HarvestJob:
```
- HarvestJob.source(HarvestSource) — direct...
Errors: 1337
- HarvestJob.items__dataset(Dataset) — embed_list...
Errors: 124347
```

**Comment by maudetes** [comment]
> We should add removing dataset from HarvestJob when purging it.

I think it is already done: https://github.com/opendatateam/udata/blob/master/udata/core/dataset/tasks.py#L51

**Comment by maudetes** [comment]
It appears that harvest job items errors all belong to harvest job that already have a `HarvestJob.source(HarvestSource)` error.

**Review by abulte — APPROVED** [review]

**Pull request merged**
