### PR TITLE
Fix typo: s/An user/A user

### LINKED ISSUE #2027: Typo in frontend: s/an user/a user
"An user" is incorrect. Replace by "A user".

### PR DESCRIPTION
**Pull request by bzg**
fix #2027

### CODE REVIEW

**Comment by bzg** [comment]
See https://github.com/opendatateam/udata/issues/2027

**Comment by abulte** [comment]
@bzg don't forget the CHANGELOG ;-)

**Comment by noirbizarre** [comment]
ie. fixes in `udata.*.json` will be overwritten except for those in `udata.en.json` which is the source file

**Comment by bzg** [comment]
Thanks for the review and the directions.

The correct way to fix strings is still not clear to me: is there a place in the documentation where I could follow a step-by-step (as in "for the n00bs") guide?

Maybe we can iterate on such instructions here and put them in the documentation later on. I'm willing to test the instructions.  Thanks!

**Comment by abulte** [comment]
There is some doc here : https://udata.readthedocs.io/en/stable/adding-translations/. 

Thing is, you need to have udata installed. If you don’t want to there’s an easier solution: just don’t commit the Json files and we’ll take care of strings extraction for you.

**Comment by abulte** [comment]
The only file you commited that’s not a JSON ;-)

**Comment by bzg** [comment]
Ok, I've read the documentation and I submitted two tiny corrections on Crowdin. I'll make another PR to update `request-modal.vue`. Thanks!

**Pull request closed without merging**
