### PR TITLE
Merge master into dev

### PR DESCRIPTION
**Pull request by noirbizarre**
This PR merge master into dev. The only real change is the map tiles switch (see #515)

### CODE REVIEW

**Comment by noirbizarre** [comment]
Wait for #517

**Comment by davidbgk** [comment]
Isn't it weird that 7 commits generated only 3 files changed, it looks suspicious to me!

**Comment by noirbizarre** [comment]
I was suprised too at first but no, It's the manual backports. They appear in the branch but they do not impact the merge commit.

**Comment by davidbgk** [comment]
Oh ok I see what you mean, r+

**Comment by noirbizarre** [comment]
I'll update as soon as the 2nd merge occurs but the diff shouldn't change

**Comment by noirbizarre** [comment]
Replaced by #519

**Pull request closed without merging**
