### PR TITLE
Fix uploader mixin import (side-effect of using ES6)

### PR DESCRIPTION
**Pull request by noirbizarre**
This PR fix a side-effect of uploader switching to ES6 syntax.

### CODE REVIEW

**Comment by davidbgk** [comment]
There are a couple of other places where we `require` directly within the `mixin` declaration, is that a problem?

**Comment by noirbizarre** [comment]
Yes, it might be if the mixin is exported with `export default`. I'm in trouble: I'm porting everything in ES6 on a branch, but to make the dev branch work until then, I have to backport these fixes :/

**Comment by davidbgk** [comment]
In that case, don't you want to change each `require('components/form/base-field').FieldComponentMixin` in that PR too?

**Comment by davidbgk** [comment]
And the change in `widgets/thumbnailer.vue` is missing too.

**Comment by noirbizarre** [comment]
Hum, I guess you're right. i'm doing this right now

**Comment by noirbizarre** [comment]
OK, fixed the missing `widgets/thumbnailer.vue` and migrated all `require('components/form/base-field').FieldComponentMixin` statements

**Comment by davidbgk** [comment]
r+

**Pull request merged**
