### PR TITLE
Feat/refacto udata docs

### PR DESCRIPTION
**Pull request by maudetes**
Fix https://github.com/etalab/data.gouv.fr/issues/398

Refactoring of udata docs.

The idea is to have the two main entry points :
- a `quickstart`, using [docker-udata](https://github.com/opendatateam/docker-udata)
- a `getting started`, with a step by step installation of udata and udata-front.

Fixed the `udata init` command for a smooth startup.

Left to do/decide:
- [x] Update extending theme documentation.
    - Should we recommend (and document only) one of the two layouts suggested?
    - Is the [Assets manifest](https://udata.readthedocs.io/en/latest/creating-theme/#assets-manifest) feature still relevant?
    - How to deal with translations?
- [x] Redirect to github discussions instead of gitter?
   - Where to host the discussions ? https://github.com/etalab/data.gouv.fr ?

### CODE REVIEW

**Review by nicolaskempf57 — APPROVED** [review]

**Comment by maudetes** [comment]
@abulte interest on your inputs on what's left to do / to decide

**Comment by abulte** [comment]
> - [ ] Update extending theme documentation.
>     - Should we recommend (and document only) one of the two layouts suggested?

Like `1-column.html`...? I'd say: document it and also explain how to add one in a new theme (if possible?)

>    - Is the [Assets manifest](https://udata.readthedocs.io/en/latest/creating-theme/#assets-manifest) feature still relevant?

Looks like it https://github.com/etalab/udata-front/blob/e94d6a8adec5fab8b90ae0c8b018f538d3db58b3/udata_front/theme/__init__.py#L74
   
>    - How to deal with translations?

Yup.

> - [ ] Redirect to github discussions instead of gitter?
>   - Where to host the discussions ? https://github.com/etalab/data.gouv.fr ?

Discussions: yes! Centralising everything on etalab/data.gouv.fr looks like a good idea _but_ there might be some discussions in English so I'm not sure. opendatateam/udata seems like a good alternative place.

**Comment by maudetes** [comment]
> >   * Should we recommend (and document only) one of the two layouts suggested?
> 
> Like `1-column.html`...? I'd say: document it and also explain how to add one in a new theme (if possible?)

I meant the two proposal that I documented [here](https://github.com/maudetes/udata/blob/feat/refacto-udata-docs/docs/creating-theme.md#project-layout) for creating a theme.

**Comment by abulte** [comment]
> I meant the two proposals that I documented [here](https://github.com/maudetes/udata/blob/feat/refacto-udata-docs/docs/creating-theme.md#project-layout) for creating a theme.

I see! I would state the second way is not recommended.

**Pull request merged**
