### PR TITLE
Escape HTML string for JS use in form description

### LINKED ISSUE #957: Login: "Forgot password" display bug
## Detailed Description
Fix the description of the password field.

capture d ecran 2017-06-08 12 20 47

## Your Environment
* Chrome 59
* macOS

### PR DESCRIPTION
**Pull request by abulte**
Fix #957 

This is probably overkill since from what I can see those descriptions are never displayed? Please advise ;-)

### CODE REVIEW

**Comment by abulte** [comment]
Possible other/further solutions:
- remove description display altogether for those forms (flask-security forms)
- display the description inline under the field (in this case we'll have a duplicate "forgot password" CTA on login)
- use `form-help` javascript tooltip like I've seen it on other parts of the site (admin)

I also find the duplicate fieldset / field label a little strange, maybe it's a good occasion to refactor those forms.

capture d ecran 2017-06-09 10 14 11

**Comment by noirbizarre** [comment]
:+1: for the factoring, let's discuss this

**Comment by davidbgk** [comment]
Escaping HTML to put it in data attributes of… HTML 🙃

Do we really need that help? Maybe `{% if f.description and '<' not in f.description %}` (your first proposal) is more pertinent here? On the screenshot it looks redundant to me.

**Comment by abulte** [comment]
No I do not think we need that (escaping). It's over engineered and useless in the context. The filter could come in handy though ;-) The best way IMHO is to refactor those forms and deal with the descriptions at this moment - remove them or display them inline?

**Comment by abulte** [comment]
PI they don't even display the field descriptions in the default `Flask-Security` templates: https://github.com/mattupstate/flask-security/blob/develop/flask_security/templates/security/_macros.html

**Comment by davidbgk** [comment]
+1 for removing them.

**Comment by abulte** [comment]
Replaced by #971.

**Pull request closed without merging**
