### PR TITLE
Add certified image on default theme

### LINKED ISSUE #972: Missing certified image on default theme
## Detailed Description

The "certified" image on an organization is missing on default theme.

capture d ecran 2017-06-14 11 13 12

## Context

When I have a certified organization, I want to see the certified image.

## Possible Implementation

Add the image from `udata-gouvfr`.

## Your Environment
* Browser Name and version: macOS
* Operating System and version (desktop or mobile): Safari desktop

### PR DESCRIPTION
**Pull request by abulte**
Fix #972

capture d ecran 2017-06-14 11 13 55

### CODE REVIEW

**Comment by davidbgk** [comment]
Idea (non-blocking): having a SVG with English text? (and convert our own to SVG too 😉)

**Comment by abulte** [comment]
Probably a good idea but (almost) no idea how to do that ¯\_(ツ)_/¯. I did not realize the text on the image was in French and that could be a problem...

**Comment by abulte** [comment]
@oncletom is looking at making a SVG version, if not we'll use a twitter-like "verified" icon instead (credits to @noirbizarre).

**Comment by abulte** [comment]
For exemple: https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/MoA-Facebook.svg/2000px-MoA-Facebook.svg.png

**Comment by abulte** [comment]
With a generic "verified" icon:

capture d ecran 2017-06-15 15 24 52

**Comment by abulte** [comment]
NB: there is a tooltip to explain the icon.

**Pull request merged**
